#### Metadaten 
Data Source: http://archive.ics.uci.edu/ml/datasets/Drug+consumption+%28quantified%29<br>
###### E. Fehrman, A. K. Muhammad, E. M. Mirkes, V. Egan and A. N. Gorban 
###### "The Five Factor Model of personality and evaluation of drug consumption risk." <br>


##### Age 
- -0.95197 18-24 643 34.11%
- -0.07854 25-34 481 25.52%
- 0.49788 35-44 356 18.89%
- 1.09449 45-54 294 15.60%
- 1.82213 55-64 93 4.93%
- 2.59171 65+ 18 0.95%

##### Gender
- 0.48246 Female 942 49.97%
- -0.48246 Male 943 50.03%

##### Education
- -2.43591 Left school before 16 years 28 1.49%
- -1.73790 Left school at 16 years 99 5.25%
- -1.43719 Left school at 17 years 30 1.59%
- -1.22751 Left school at 18 years 100 5.31%
- -0.61113 Some college or university, no certificate or degree 506 26.84%
- -0.05921 Professional certificate/ diploma 270 14.32%
- 0.45468 University degree 480 25.46%
- 1.16365 Masters degree 283 15.01%
- 1.98437 Doctorate degree 89 4.72%

##### Country
- -0.09765 Australia 54 2.86%
- 0.24923 Canada 87 4.62%
- -0.46841 New Zealand 5 0.27%
- -0.28519 Other 118 6.26%
- 0.21128 Republic of Ireland 20 1.06%
- 0.96082 UK 1044 55.38%
- -0.57009 USA 557 29.55%

##### Ethnicity
- -0.50212 Asian 26 1.38%
- -1.10702 Black 33 1.75%
- 1.90725 Mixed-Black/Asian 3 0.16%
- 0.12600 Mixed-White/Asian 20 1.06%
- -0.22166 Mixed-White/Black 20 1.06%
- 0.11440 Other 63 3.34%
- -0.31685 White 1720 91.25%

##### Neo Five-Factor Inventory (OCEAN)
https://dorsch.hogrefe.com/stichwort/neo-fuenf-faktoren-inventar-neo-ffi<br>
https://en.wikipedia.org/wiki/Revised_NEO_Personality_Inventory<br>
https://www.sciencedirect.com/science/article/abs/pii/S0191886904001394<br>

- Nscore for Neuroticism: 60 items (12 per domain)
- Escore for Extraversion
- Oscore for Openess to new experiences
- Ascore for Agreeableness
- Cscore for Concientiousness


##### Impulsiveness measured by BIS-11

##### Sensation Seeking Behaviour measured by ImpSS

##### Drugs
- Alcohol
- Amphetamines
- Amyl
- Benzodiazepine (hier aufpassen, oft ohne Eigenverschulden, danke Pharma)
- Caffeine
- Cannabis
- Chocolate
- Cocaine
- Crack
- Ecstasy
- Heroin
- Ketamine
- Legal highs
- LSD
- Methamphetamine 
- Mushrooms
- Nicotine
- Semer (Fictitious drug Semeron)
- VSA 


##### Consumed (Timeframe)
- CL0: Never
- CL1: Over Decade ago
- CL2: In last Decade
- CL3: Last Year
- CL4: Last Month
- CL5: Last Week
- CL6: Last Day

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
df = pd.read_excel('drug_consumption.xls')

In [3]:
df.shape

(1885, 32)

In [4]:
df.head()

,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,Impulsive,SS,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Shrooms,Nicotine,Semer,VSA
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,CL5,CL2,CL0,CL2,CL6,CL0,CL5,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,CL5,CL2,CL2,CL0,CL6,CL4,CL6,CL3,CL0,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,CL6,CL0,CL0,CL0,CL6,CL3,CL4,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,CL4,CL0,CL0,CL3,CL5,CL2,CL4,CL2,CL0,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,CL4,CL1,CL1,CL0,CL6,CL3,CL6,CL0,CL0,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0

In [19]:
df.isna().sum()

Age                  0
Gender               0
Education            0
Country              0
Ethnicity            0
Neuroticism          0
Extraversion         0
Openness             0
Agreeableness        0
Conscientiousness    0
Impulsiveness        0
Sensations           0
Alcohol              0
Amphet               0
Amyl                 0
Benzos               0
Caff                 0
Cannabis             0
Choc                 0
Coke                 0
Crack                0
Ecstasy              0
Heroin               0
Ketamine             0
Legalh               0
LSD                  0
Meth                 0
Shrooms              0
Nicotine             0
Semer                0
VSA                  0
dtype: int64

##### Change Age, Gender, Country, Ethnicity, Education for EDA and rename Columns

In [5]:
df = df.rename(columns={'Nscore': 'Neuroticism', 
                        'Escore': 'Extraversion', 
                        'Oscore': 'Openness', 
                        'Ascore': 'Agreeableness', 
                        'Cscore': 'Conscientiousness', 
                        'Impulsive': 'Impulsiveness', 
                        'SS': 'Sensations'})

In [6]:
df.dtypes

ID                     int64
Age                  float64
Gender               float64
Education            float64
Country              float64
Ethnicity            float64
Neuroticism          float64
Extraversion         float64
Openness             float64
Agreeableness        float64
Conscientiousness    float64
Impulsiveness        float64
Sensations           float64
Alcohol               object
Amphet                object
Amyl                  object
Benzos                object
Caff                  object
Cannabis              object
Choc                  object
Coke                  object
Crack                 object
Ecstasy               object
Heroin                object
Ketamine              object
Legalh                object
LSD                   object
Meth                  object
Shrooms               object
Nicotine              object
Semer                 object
VSA                   object
dtype: object

In [7]:
# ID
# will not be used in Model
df = df.drop('ID', axis=1)

In [8]:
df.loc[df.Age == -0.95197, "Age"]= '(18-24)'
df.loc[df.Age == -0.07854, "Age"]= '(25-34)'
df.loc[df.Age == 0.49788, "Age"]= '(35-44)'
df.loc[df.Age == 1.09449, "Age"]= '(45-54)'
df.loc[df.Age == 1.82213, "Age"]= '(55-64)'
df.loc[df.Age == 2.59171, "Age"]= '(65+)'

In [9]:
df.Gender = ['male' if i == -0.48246 else 'female' for i in df.Gender]

In [10]:
df.loc[df.Country == 0.96082, "Country"]= 'UK'
df.loc[df.Country == -0.57009, "Country"]= 'USA'
df.loc[df.Country == -0.28519, "Country"]= 'Other'
df.loc[df.Country == 0.24923, "Country"]= 'Canada'
df.loc[df.Country == -0.09765, "Country"]= 'Australia'
df.loc[df.Country == 0.21128, "Country"]= 'Ireland'
df.loc[df.Country == -0.46841, "Country"]= 'NewZealand'

In [11]:
df.loc[df.Ethnicity == -0.31685, "Ethnicity"]= 'White'
df.loc[df.Ethnicity == 0.11440, "Ethnicity"]= 'Other'
df.loc[df.Ethnicity == -1.10702, "Ethnicity"]= 'Black'
df.loc[df.Ethnicity == -0.50212, "Ethnicity"]= 'Asian'
df.loc[df.Ethnicity == -0.22166, "Ethnicity"]= 'Mixed-White/Black'
df.loc[df.Ethnicity == 0.12600, "Ethnicity"]= 'Mixed-White/Asian'
df.loc[df.Ethnicity == 1.90725, "Ethnicity"]= 'Mixed-Black/Asian'

In [12]:
# Asumption: starts school at six years
df.loc[df.Education == -0.61113, "Education"]= 'Undergrad'
df.loc[df.Education == 0.45468, "Education"]= 'Uni'
df.loc[df.Education == 1.16365, "Education"]= 'Masters'
df.loc[df.Education == -0.05921, "Education"]= 'Professional'
df.loc[df.Education == -1.22751, "Education"]= '12'
df.loc[df.Education == -1.73790, "Education"]= '10'
df.loc[df.Education == 1.98437, "Education"]= 'PHD'
df.loc[df.Education == -1.43719, "Education"]= '11'
df.loc[df.Education == -2.43591, "Education"]= 'Under 10'

In [16]:
df.head()

,Age,Gender,Education,Country,Ethnicity,Neuroticism,Extraversion,Openness,Agreeableness,Conscientiousness,Impulsiveness,Sensations,Alcohol,Amphet,Amyl,Benzos,Caff,Cannabis,Choc,Coke,Crack,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Shrooms,Nicotine,Semer,VSA
0,(35-44),female,Professional,UK,Mixed-White/Asian,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,-0.21712,-1.18084,CL5,CL2,CL0,CL2,CL6,CL0,CL5,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,(25-34),male,PHD,UK,White,-0.67825,1.93886,1.43533,0.76096,-0.14277,-0.71126,-0.21575,CL5,CL2,CL2,CL0,CL6,CL4,CL6,CL3,CL0,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,(35-44),male,Professional,UK,White,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,-1.37983,0.40148,CL6,CL0,CL0,CL0,CL6,CL3,CL4,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,(18-24),female,Masters,UK,White,-0.14882,-0.80615,-0.01928,0.59042,0.58489,-1.37983,-1.18084,CL4,CL0,CL0,CL3,CL5,CL2,CL4,CL2,CL0,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,(35-44),female,PHD,UK,White,0.73545,-1.63340,-0.45174,-0.30172,1.30612,-0.21712,-0.21575,CL4,CL1,CL1,CL0,CL6,CL3,CL6,CL0,CL0,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0

In [17]:
df.groupby('Ethnicity')['Neuroticism'].mean()

Ethnicity
Asian                0.045161
Black               -0.292571
Mixed-Black/Asian    0.670877
Mixed-White/Asian    0.393614
Mixed-White/Black    0.040229
Other               -0.020548
White               -0.000480
Name: Neuroticism, dtype: float64

In [13]:
# People who consume Semeron can't be trusted. Drop them. 
df.Semer.value_counts()

CL0    1877
CL2       3
CL1       2
CL3       2
CL4       1
Name: Semer, dtype: int64

In [15]:
# Benzos is it's own problem. Often not consumed for fun, but taken due to lax prescription policy and pharma pressure
# Check, it this theory holds